Repository 9oormthon-univ/2025_SEASONTHON_TEAM_17_FE, pull requests merged in 2025-09, with the labels that each got.

#32 feat: divider 컴포넌트 구현
  src/shared/components/divider.tsx
Labels: 경수, 🎨 UI 구현

#36 style: 캘린더 디자인 변경사항 반영
  src/pages/diary/diary-page.tsx
  src/shared/components/calendar/calendar.tsx
Labels: 소은, 🎨 UI 구현

#40 feat: 알림 페이지 구현
  src/pages/notifications/notifications-page.tsx
  src/shared/assets/images/noti-bg.png
Labels: 소은, 🎨 UI 구현

#41 feat: 나의 일기 기록 1차 퍼블리싱
  src/pages/diary/diary-page.tsx
  src/pages/diary/diary-record-page.tsx
  src/shared/layouts/layout.tsx
  src/shared/layouts/nav-bar.tsx
  src/shared/styles/theme.css
Labels: 소은, 🎨 UI 구현

#42 feat: 카드 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/shared/components/card/diary-card.tsx
  src/shared/components/card/emotion-card.tsx
  src/shared/components/chips/chips.tsx
Labels: 경수, 🎨 UI 구현

#53 style: splash 수정
  src/shared/layouts/layout.tsx
  src/shared/layouts/splash.tsx
Labels: 소은, 🎨 UI 구현

#48 feat: homepage 퍼블리싱
  src/pages/home/components/hero-section.tsx
  src/pages/home/home.tsx
  src/shared/routes/router.tsx
Labels: 지훈, 🎨 UI 구현

#54 feat: 웹 FCM + PWA 기본 세팅
  dev-dist/registerSW.js
  dev-dist/sw.js
  dev-dist/workbox-86c9b217.js
  package.json
  pnpm-lock.yaml
  public/firebase-messaging-sw.js
  public/logo-192.png
  public/logo-512.png
  src/pages/main/main-page.tsx
  src/pages/my-page/components/inquiry-alerts-section.tsx
  src/pages/my-page/components/setting-row.tsx
  src/pages/my-page/my-page.tsx
  src/pages/my-page/utils/file-to-data.ts
  src/pages/notifications/notifications-page.tsx
  src/shared/components/toast.tsx
  src/shared/constants/.gitkeep
  src/shared/constants/fcm.ts
  src/shared/constants/toast-messages.ts
  src/shared/contexts/toast-context.tsx
  src/shared/hooks/use-fcm.ts
  src/shared/libs/firebase.ts
  vite.config.ts
Labels: ⚒️ setting, 소은

#60 feat: 친구 상세 페이지 뷰 퍼블리싱
  dev-dist/sw.js
  src/pages/friends/components/friends-list-item.tsx
  src/pages/friends/friend-detail-page.tsx
  src/pages/friends/friend-diary-page.tsx
  src/pages/friends/friends-page.tsx
  src/shared/layouts/layout.tsx
  src/shared/routes/router.tsx
Labels: 소은, 🎨 UI 구현

#57 feat: 일기 작성하기 1차 퍼블리싱
  src/pages/diary/components/loading-spinner.tsx
  src/pages/diary/components/loading.tsx
  src/pages/diary/components/toggle-button.tsx
  src/pages/diary/constants/diary-complete.ts
  src/pages/diary/diary-create-page.tsx
  src/pages/diary/diary-result-page.tsx
  src/shared/layouts/layout.tsx
  src/shared/routes/router.tsx
Labels: 경수, 🎨 UI 구현

#70 feat: FCM, 친구 관련 API 연동
  public/firebase-messaging-sw.js
  src/App.tsx
  src/firebase/fcm.ts
  src/firebase/firebase.ts
  src/pages/friends/components/friends-list-item.tsx
  src/pages/friends/friend-detail-page.tsx
  src/pages/friends/friends-more-page.tsx
  src/pages/friends/friends-page.tsx
  src/pages/notifications/notifications-page.tsx
  src/shared/apis/factory.ts
  src/shared/apis/fcm/fcm-queries.ts
  src/shared/apis/friends/friends-queries.ts
  src/shared/hooks/use-fcm.ts
Labels: ⚒️ setting, 소은, API 연동

#74 feat: fcm 사파리 대응을 위해 적용 시점 수정
  src/App.tsx
  src/pages/main/components-test-page.tsx
  src/pages/my-page/components/inquiry-alerts-section.tsx
  src/pages/my-page/components/toggle-switch.tsx
  src/pages/my-page/hooks/use-logout.ts
  src/pages/my-page/my-page.tsx
  src/shared/routes/auth-guard.ts
  src/shared/routes/router.tsx
Labels: ⚙️ 기능 구현, 소은

#83 feat: 일기 privateSetting(토글) 반영
  src/pages/diary/diary-page.tsx
  src/pages/diary/diary-record-page.tsx
  src/shared/apis/diaries/diaries.ts
  src/shared/components/card/diary-card.tsx
Labels: 지훈, API 연동

#88 feat: 일기 삭제 API 연동
  src/pages/diary/constants/diary-emotions.ts
  src/pages/diary/diary-page.tsx
  src/pages/diary/diary-record-page.tsx
  src/shared/components/bottom-sheet/delete-confirm-sheet.tsx
  src/shared/components/card/diary-card.tsx
Labels: 지훈, API 연동

#90 feat: 친구 상세 api 로직 수정 및 유저 조회 api 연동
  .github/workflows/deploy-prod.yml
  public/firebase-messaging-sw.js
  src/App.tsx
  src/firebase/fcm.ts
  src/firebase/firebase.ts
  src/pages/friends/components/friends-list-item.tsx
  src/pages/friends/components/friends-list.tsx
  src/pages/friends/friend-detail-page.tsx
  src/pages/friends/friend-diary-page.tsx
  src/pages/friends/friends-more-page.tsx
  src/pages/friends/friends-page.tsx
  src/pages/friends/utils/get-error-toast-msg.ts
  src/pages/friends/utils/normalize.ts
  src/pages/friends/utils/to-detail-vm.ts
  src/pages/main/components/hero-section.tsx
  src/pages/main/main-page.tsx
  src/pages/my-page/components/toggle-switch.tsx
  src/pages/my-page/my-page.tsx
  src/shared/apis/constants/endpoints.ts
  src/shared/apis/constants/keys.ts
  src/shared/apis/diaries/diaries-queries.ts
  src/shared/apis/members/members-queries.ts
  src/shared/apis/members/members.ts
  src/shared/hooks/fcm-foreground.tsx
  src/shared/hooks/use-fcm.ts
  src/shared/layouts/layout.tsx
  src/shared/layouts/nav-bar.tsx
  src/shared/libs/firebase.ts
  src/shared/routes/router.tsx
Labels: 소은, API 연동

#94 feat: 메인 페이지 차트 ui 수정 및 감정 분석 api 연동
  src/pages/main/components/emotion-bar-chart.tsx
  src/pages/main/components/emotion-stats-section.tsx
  src/pages/main/main-page.tsx
  src/shared/apis/constants/endpoints.ts
  src/shared/apis/emotions/emotion-queries.ts
Labels: 소은, 🎨 UI 구현, API 연동

#95 feat: 오늘 일기 중복 체크 api 연동
  src/pages/diary/diary-page.tsx
Labels: 경수, API 연동

#96 feat: like api 연동 및 토글 중복 선택 방지
  src/pages/diary/diary-page.tsx
  src/pages/diary/diary-record-page.tsx
  src/pages/diary/stores/emotion-like-store.ts
  src/pages/friends/friend-diary-page.tsx
  src/shared/apis/diaries/diaries.ts
Labels: 지훈, API 연동

#97 feat: Toggle API 연동
  src/pages/diary/diary-page.tsx
  src/pages/diary/diary-record-page.tsx
  src/shared/components/card/diary-card.tsx
Labels: 경수, API 연동
